//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelationshipMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ttile
    {
        public int TitleID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string DateTitled { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Yehicle Yehicle { get; set; }
    }
}
